services:
  app:
    image: "marceauh/epimethee:latest"
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_PASSWORD=secret
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
        - REDIS_PASSWORD=secret
